### ISSUE TITLE
unknown command thin_trim 

### ISSUE THREAD

**Issue by nobluesky** [jthornber/thin-provisioning-tools#26] opened 2015-05-11 20:31 UTC
i built it from master branch. 
but i can't run thin_trim

Unknown command 'thin_trim'
Usage: <command> <args>
commands:
  cache_check
  cache_dump
  cache_metadata_size
  cache_restore
  cache_repair
  era_check
  era_dump
  era_invalidate
  era_restore
  thin_check
  thin_delta
  thin_dump
  thin_metadata_size
  thin_restore
  thin_repair
  thin_rmap

**Comment by tyll** [comment] 2016-03-03 11:55
This is a duplicate of #24

**Closed** 2017-10-09 13:01 UTC
